[uwsgi]
master = true
http=:80
chdir = /opt/code_files/personal_web_page
wsgi-file=start.py
callable=app
processes=4
threads=2
buffer-size = 65536
vacuum=true
pidfile =uwsgi.pid
daemonize =log/uwsgi.log